# Basic Spring Boot Config for Oracle and hibernate config
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@10.30.49.76:1521/ORADB
        username: basis
        password: erpbasis0
#        url: jdbc:oracle:thin:@192.168.147.143:1521/xe
#        username: system
#        password: oracle
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        show-sql: true

# Redis properties
    redis:
        port: 6379
        host: 11.11.47.72
#        host: 192.168.147.143
#        host: ${REDIS_HOST}
        pool:
            maxIdle: 8 # max idle connections in the pool
            minIdle: 0 # min idle connections in the pool
            maxActive: -1 # no limit to the number of active connections
            maxWait: 30000 # time limit to get a connection - only applies if maxActive is finite

    mail:
        host: mail.cnpc.com.cn
        username: erpyyjcadmin@cnpc.com.cn
        password: bgp123
#        host: smtp.163.com
#        username: hpxue13@163.com
#        password: 8121812
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 25000
        default-encoding: UTF-8
        users:
            leader:
                username: wangqian
                name: 王茜
                mail: wangqian91@cnpc.com.cn
            staff:
                - username: hushuai
                  name: 胡帅
                  mail: hushuai@cnpc.com.cn
                - username: hanxinyi
                  name: 韩心怡
                  mail: hanxinyi3@cnpc.com.cn
                - username: zhouwei
                  name: 周惟
                  mail: zhouwei04@cnpc.com.cn
                - username: jiangyongrui
                  name: 姜永锐
                  mail: jiangyongrui@cnpc.com.cn
                - username: zhaoxin
                  name: 赵鑫
                  mail: zhaoxin01@cnpc.com.cn
                - username: jiaolong
                  name: 焦龙
                  mail: jiaolong@cnpc.com.cn
                - username: wangyubo
                  name: 王禹博
                  mail: wangyubo02@cnpc.com.cn
                - username: wenduzi
                  name: 文都子
                  mail: wenduzi@cnpc.com.cn
                - username: xuehaipeng
                  name: 薛海鹏
                  mail: xuehaipeng@cnpc.com.cn
                - username: hesiyang
                  name: 何思洋
                  mail: hesiyang3@cnpc.com.cn

# Sftp Configuration
# Non-SAP DB backup polling
storage:
    multipart:
        upload-dir: D:\Work\upload

sftp:
    ips:
    # PRD
        - 10.30.37.11
        - 11.11.3.58
        - 11.11.4.58
        - 11.11.3.250
        - 10.30.36.56
        - 10.30.36.11
        - 10.30.36.8
        - 10.30.49.48
        - 10.30.36.55
        - 10.30.36.56
        - 10.30.36.67
        - 10.30.148.121
        - 10.30.150.251
        - 10.30.147.122
        - 10.30.37.251
        - 11.11.5.250
        - 10.30.35.123
        - 11.11.3.121
        - 10.30.147.132
        - 11.11.3.186
        - 10.30.35.187
        - 10.30.35.251
        - 11.11.70.74
        - 11.11.70.75
        - 10.30.148.120
        - 10.30.148.119
    # QAS
        - 10.30.47.96
        - 10.30.47.97
        - 11.11.49.134
        - 10.30.47.100
        - 11.11.49.43
        - 10.30.49.70
        - 10.30.47.17
        - 10.30.49.72
        - 10.30.47.182
        - 10.30.47.52
        - 11.11.49.71
        - 10.30.47.70
        - 11.11.49.69
        - 10.30.47.74
        - 11.11.49.70
        - 10.30.47.76
        - 10.30.47.71
        - 10.30.49.92
    # DEV
        - 10.30.47.138
        - 10.30.47.139
        - 11.11.49.132
        - 10.30.47.142
        - 10.30.47.187
        - 10.30.47.152
        - 10.30.49.69
        - 10.30.47.16
        - 10.30.49.64
        - 10.30.47.165
        - 10.30.47.103
        - 11.11.49.68
        - 10.30.47.118
        - 11.11.49.66
        - 10.30.47.122
        - 11.11.49.67
        - 10.30.47.124
        - 10.30.47.120
        - 10.30.49.94

    username: itmuser
    passwd: itmuser
    remoteFile: /usr/openv/sap_oracle/hot_database_backup.sh.out
    
# Ssh Configuration
ssh:
    ip: 10.30.47.218
    username: wladm
    passwd: mybasis0
    cmd:
        - df -h
        - ifconfig

# NBU for SAP backup check
sap:
    hosts:
#        HP1: 1.4.1.1188
        CP6: 10.30.147.17
        CPF: 11.11.3.18
        CPO: 11.11.3.202
    logfiles:
    # SAP DB backup polling
    # PRD
        10.30.148.8: /oracle/GP1/sapbackup/backGP1001.log
        10.30.147.17: /oracle/CP6/sapbackup/backCP6002.log
        11.11.3.18: /oracle/CPF/sapbackup/backCPF001.log
        11.11.3.202: /oracle/CPO/sapbackup/backCPO001.log
        10.30.147.26: /oracle/EP6/sapbackup/backEP6001.log
        10.30.147.33: /oracle/EP7/sapbackup/backEP7001.log
        11.11.3.149: /oracle/COP/sapbackup/backCOP002.log
        11.11.3.74: /oracle/EP9/sapbackup/backEP9001.log
        11.11.5.213: /oracle/EMP/sapbackup/backEMP001.log
        10.30.36.157: /oracle/EP1/sapbackup/backEP1001.log
        11.11.49.105: /oracle/JP1/sapbackup/backJP1.log
        10.30.35.68: /oracle/BP9/sapbackup/backBP9001.log
        10.30.37.195: /oracle/BPD/sapbackup/backBPD001.log
        10.30.35.132: /oracle/BPC/sapbackup/backBPC001.log
    # QAS
        10.30.47.223: /oracle/EQ6/sapbackup/backEQ6.log
        10.30.47.226: /oracle/EQ7/sapbackup/backEQ7.log
        11.11.49.84: /oracle/COQ/sapbackup/backCOQ.log
        11.11.49.86: /oracle/EQ9/sapbackup/backEQ9.log
        11.11.49.80: /oracle/EMQ/sapbackup/backEMQ.log
        10.30.47.208: /oracle/EQ1/sapbackup/backEQ1.log
        10.30.47.73: /oracle/BQ9/sapbackup/backBQ9.log
        10.30.47.75: /oracle/BQC/sapbackup/backBQC.log
        10.30.47.69: /oracle/BQD/sapbackup/backBQD.log
        11.11.49.55: /oracle/HQ1/sapbackup/backHQ1.log
        10.30.47.201: /oracle/CQ6/sapbackup/backCQ6.log
        11.11.49.120: /oracle/CQF/sapbackup/backCQF.log
        11.11.49.238: /oracle/CQO/sapbackup/backCQO.log
        10.30.47.176: /oracle/GQ1/sapbackup/backGQ1.log
    #DEV
        10.30.47.222: /oracle/ED6/sapbackup/backED6.log
        10.30.47.225: /oracle/ED7/sapbackup/backED7.log
        11.11.49.83: /oracle/COD/sapbackup/backCOD.log
        11.11.49.85: /oracle/ED9/sapbackup/backED9.log
        11.11.49.79: /oracle/EMD/sapbackup/backEMD.log
        10.30.47.207: /oracle/ED1/sapbackup/backED1.log
        10.30.47.121: /oracle/BD9/sapbackup/backBD9.log
        10.30.47.123: /oracle/BDC/sapbackup/backBDC.log
        10.30.47.117: /oracle/BDD/sapbackup/backBDD.log
        11.11.49.54: /oracle/HD1/sapbackup/backHD1.log
        10.30.47.12: /oracle/CD6/sapbackup/backCD6.log
        10.30.47.22: /oracle/CDF/sapbackup/backCDF.log
        11.11.49.237: /oracle/CDO/sapbackup/backCDO.log
        11.11.49.106: /oracle/JD1/sapbackup/backJD1.log
        10.30.47.159: /oracle/GD1/sapbackup/backGD1.log
    username: itmuser
    passwd: itmuser
