# Basic Spring Boot Config for Oracle and hibernate config
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@10.30.49.77:1521/ORADB
        username: basis
        password: erpbasis0
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        show-sql: true

# Sftp Configuration
sftp:
    ips:
        - 10.30.37.11
        - 11.11.3.58
        - 11.11.4.58
        - 11.11.3.250
        - 10.30.36.56
        - 10.30.36.11
        - 10.30.36.8
        - 10.30.47.97
        - 10.30.47.96
        - 10.30.49.48
        - 10.30.36.55
        - 10.30.36.56
        - 10.30.36.67
        - 10.30.148.121
        - 10.30.150.251
        - 10.30.147.122
        - 10.30.37.251
        - 11.11.5.250
        - 10.30.35.123
        - 11.11.3.121
        - 10.30.147.132
        - 11.11.3.186
        - 10.30.35.187
        - 10.30.35.251
    username: itmuser
    passwd: itmuser
    remoteFile: /usr/openv/sap_oracle/hot_database_backup.sh.out
    
# Ssh Configuration
ssh:
    ip: 10.30.47.218
    username: wladm
    passwd: mybasis0
    cmd:
        - df -h
        - ifconfig