# Basic Spring Boot Config for Oracle and hibernate config
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@10.30.49.77:1521/ORADB
        username: basis
        password: erpbasis0
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        show-sql: true

# Sftp Configuration
sftp:
    ips:
        - 10.30.36.56
        - 10.30.47.97
        - 10.30.47.96
        - 10.30.49.48
        - 10.30.36.55
        - 10.30.36.56
        - 10.30.37.11
        - 11.11.3.58
        - 11.11.3.250
    username: itmuser
    passwd: itmuser
    remoteFile: /usr/openv/sap_oracle/hot_database_backup.sh.out
    
# Ssh Configuration
ssh:
    ip: 10.30.47.218
    username: wladm
    passwd: mybasis0
    cmd:
        - df -h
        - ifconfig