# Basic Spring Boot Config for Oracle and hibernate config
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@10.30.49.77:1521/ORADB
        username: basis
        password: erpbasis0
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        show-sql: true

# Sftp Configuration
sftp:
    ip: 10.30.47.218
    username: wladm
    passwd: mybasis0
    remoteFile: /usr/openv/sap_oracle/hot_database_backup.sh.out
    
# Ssh Configuration
ssh:
    ip: 10.30.47.218
    username: wladm
    passwd: mybasis0
    cmd:
        - df -h
        - ifconfig